// Uses Declarative syntax to run commands inside a container.
pipeline {
  agent { label 'migration' }

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    disableConcurrentBuilds()
  }

/*
  environment {
    BUILD_JRE_SCRIPT = '''
'''
  }
*/

  stages {
    stage('Setup Environment') {
      steps {
        sh '''
        echo 'Setting up environment...'
        ls -R releng
        chmod +x releng/org.eclipse.justj.releng/*.sh
        '''
        stash includes: 'releng/org.eclipse.justj.releng/**', name: 'releng-stash'
      }
    }

    stage('Build JRE') {
      parallel {

        stage('Linux') {
          steps {
            sh '''
            releng/org.eclipse.justj.releng/test.sh
            '''
            // archiveArtifacts '*.result'
            // archiveArtifacts 'org.eclipse.justj.*.tar.gz'
          }
        }
        stage('Windows') {
          agent { label 'windows' }
          options { skipDefaultCheckout true }
          steps {
            cleanWs()
            unstash 'releng-stash'
            bat '''
               bash -ex -c "ls -R"
               bash -ex releng/org.eclipse.justj.releng/test.sh
               '''
//            bat '''
//              bash -ex -c "eval ""$BUILD_JRE_SCRIPT"""
//              '''
//            archiveArtifacts 'org.eclipse.justj.*.tar.gz'
//            stash includes: '*org.eclipse.justj.*.tar.gz', name: 'win-stash'
           stash includes: '*.result', name: 'win-stash'
          }
        }

        stage('MacOS') {
          agent { label 'macos' }
          options { skipDefaultCheckout true }
          steps {
            cleanWs()
            sh '''
            releng/org.eclipse.justj.releng/test.sh
            '''
//          stash includes: '*.result', name: 'mac-stash'
//            sh '''
//               eval "$BUILD_JRE_SCRIPT"
//              '''
//            archiveArtifacts 'org.eclipse.justj.*.tar.gz'
//            stash includes: 'org.eclipse.justj.*.tar.gz', name: 'mac-stash'
          }
        }
      }
    }

    stage('Compose Results') {
      steps {
        unstash 'mac-stash'
        unstash 'win-stash'
        sh 'ls *.result'
        archiveArtifacts '*.result'
        /*
        sh 'ls -al org.eclipse.justj.*.tar.gz'
        sh 'ls org.eclipse.justj.*.tar.gz > justj.manifest'
        sshagent(['projects-storage.eclipse.org-bot-ssh']) {
          sh '''
            TIMESTAMP=$(date '+%Y%m%d_%H%M%S')
            ssh genie.justj@projects-storage.eclipse.org "
            ls -al /home/data/httpd/download.eclipse.org/justj/sandbox/jres
            mkdir -p /home/data/httpd/download.eclipse.org/justj/sandbox/jres/$TIMESTAMP
            "

            scp justj.manifest org.eclipse.justj.*.tar.gz genie.justj@projects-storage.eclipse.org:/home/data/httpd/download.eclipse.org/justj/sandbox/jres/$TIMESTAMP

            ssh genie.justj@projects-storage.eclipse.org "
            mkdir -p /home/data/httpd/download.eclipse.org/justj/sandbox/jres/latest
            cd /home/data/httpd/download.eclipse.org/justj/sandbox/jres/latest
            ls ../$TIMESTAMP/org.eclipse.justj.*.tar.gz > justj.manifest
            "
            '''
        }
        */
      }
    }
  }

/*
  post {
    failure {
      mail to: 'ed.merks@gmail.com',
      subject: "[JustJ CI] Build Failure ${currentBuild.fullDisplayName}",
      mimeType: 'text/html',
      body: "Project: ${env.JOB_NAME}<br/>Build Number: ${env.BUILD_NUMBER}<br/>Build URL: ${env.BUILD_URL}<br/>Console: ${env.BUILD_URL}/console"
    }
    fixed {
      mail to: 'ed.merks@gmail.com',
      subject: "[JustJ CI] Back to normal ${currentBuild.fullDisplayName}",
      mimeType: 'text/html',
      body: "Project: ${env.JOB_NAME}<br/>Build Number: ${env.BUILD_NUMBER}<br/>Build URL: ${env.BUILD_URL}<br/>Console: ${env.BUILD_URL}/console"
    }
    cleanup {
      deleteDir()
    }
  }
*/
}
